imports:
  - {resource: 'EXT:taskhub/Configuration/Routes/Detail.yaml' }

base: 'https://taskhub.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
  -
    title: Deutsch
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=8'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\nDisallow: /typo3/\nDisallow: /typo3conf/\nAllow: /typo3conf/ext/\n\nSitemap: https://www.example.com/sitemap.xml"
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=9&type=1533906435'


rootPageId: 1
websiteTitle: 'Taskhub'
