#!/bin/bash

## Description: Setup the TYPO3 project
## Usage: setup
## Example: "ddev setup"
## ProjectTypes: typo3
## ExecRaw: true

rm -rf var/cache || true
ddev composer install
echo "DROP DATABASE db; CREATE DATABASE db;" | ddev mysql
ddev import-db --file="./Build/db.sql.gz"
ddev typo3 install:setup --skip-integrity-check
cp .Build/public/typo3/sysext/install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .Build/public
mv .Build/public/root-htaccess .Build/public/.htaccess
ddev typo3 cache:flush
ddev launch
