services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RZT\Taskhub\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  RZT\Taskhub\EventListener\GenerateTaskSlug:
    tags:
      - name: event.listener
        identifier: generateTaskSlug
        event:   RZT\Taskhub\Event\AfterCreateTaskEvent
